#!/bin/sh
login=definitly
proc=dzen2
file=/home/$login/.config/openbox/rc.xml
file2=/home/$login/.config/openbox/rc.xml_new

   
                cat $file | sed 's/<top>0<\/top>/<top>14<\/top>/' > $file2
                mv $file2 $file
                openbox --reconfigure
          
          if ! [ -z $(pgrep $proc) ]
                then
                   killall -9 dzen2
                   cat $file | sed 's/<top>14<\/top>/<top>0<\/top>/' > $file2
                   mv $file2 $file
                   openbox --reconfigure
          
                else
                    dzenconky &
          fi
           