#!/bin/sh





  #unmount  /compat/linux/proc if mounted
       
      
         



      if ! [ -z "$(mount | grep linprocfs)" ]; then 
       
           daos   umount  /compat/linux/proc

      fi
                 
           



 

    if  [ -z "$(mount | grep nullfs )" ]; then 
       
       daos mount -t nullfs /compat/ubuntu/ /compat/linux/

    fi


    if  [ -z "$(mount | grep linprocfs)" ]; then 
       
       daos mount -t linprocfs linproc /compat/linux/proc

    fi

      
    

   if  [ -z "$(mount | grep tmpfs)" ]; then
       
  
     daos mount -t tmpfs tmpfs /compat/linux/var/run/shm
                       
   fi



    if  [ -z "$(mount | grep linsysfs)" ]; then
       
       daos mount -t linsysfs linsys /compat/linux/sys
                       
   fi



       
       daos chmod 1777 /compat/linux/var/run/shm
    
  


          
echo -n "нажмите enter что бы отмонтировать разделы "
read text
   

       daos umount -f  /compat/linux/proc
       daos umount -f  /compat/linux/var/run/shm
       daos umount -f  /compat/linux/sys
       daos umount -f  /compat/linux

      if  [  -z "$(mount | grep linprocfs )" ]; then
          daos mount -t linprocfs linproc /compat/linux/proc
      fi


       