#!/bin/sh



  #unmount  /compat/linux/proc if mounted
       
      
           if  ! [  -f "$HOME/.steam/steamrun.pid" ];then



      if  [ -z "$(mount | grep linprocfs)" ]; then 
       

       else
       sudo   umount  /compat/linux/proc

      fi
                 
           fi



 

    if  [ -z "$(mount | grep nullfs )" ]; then 
       
       sudo mount -t nullfs /compat/ubuntu/ /compat/linux/

    fi


    if  [ -z "$(mount | grep linprocfs)" ]; then 
       
       sudo mount -t linprocfs linproc /compat/linux/proc

    fi

      

     


 

   if  [ -z "$(mount | grep tmpfs)" ]; then
       
       sudo mount -t tmpfs tmpfs /compat/linux/dev/shm
                       
   fi



    if  [ -z "$(mount | grep linsysfs)" ]; then
       
       sudo mount -t linsysfs linsys /compat/linux/sys
                       
   fi



       
       sudo chmod 1777 /compat/linux/dev/shm
       sudo chmod 1777 /compat/linux/tmp
  



    if ! [ -d  "$HOME/.steam/sdk32/"  ]; then

   

       mkdir -p  $HOME/.steam/sdk32/


   fi

       

  
      if ! [ -f $HOME/.steam/steam/ubuntu12_32/steamwebhelper ]; then

           mv     $HOME/.steam/steam/ubuntu12_32/steamwebhelper.bak     $HOME/.steam/steam/ubuntu12_32/steamwebhelper

       fi



       if ! [ -f $HOME/.steam/sdk32/steamclient.so ]; then

           ln -s    $HOME/.steam/steam/linux32/steamclient.so       $HOME/.steam/sdk32/steamclient.so

       fi

              export LD_LIBRARY_PATH=$HOME/.local/share/Steam/ubuntu12_32
       
              $HOME/.local/share/Steam/ubuntu12_32/steam  $1 &

              echo $! > $HOME/.steam/steamrun.pid


              sleep 2 

              mv $HOME/.steam/steam/ubuntu12_32/steamwebhelper $HOME/.steam/steam/ubuntu12_32/steamwebhelper.bak
 
    

   while ! [  -z "$(ps aux | grep "$HOME[/].local/share/Steam/ubuntu12_32/steam")" ] 

   do
   sleep 1.5

   done 
 
              rm $HOME/.steam/steamrun.pid



       sudo umount -f  /compat/linux/proc
       sudo umount -f  /compat/linux/dev/shm
       
       sudo umount -f  /compat/linux/sys
       sudo umount -f  /compat/linux

      if  [  -z "$(mount | grep linprocfs )" ]; then
          sudo mount -t linprocfs linproc /compat/linux/proc
      fi


       