#!/bin/sh
kldload linux
tar xf ./pkg-1.1.4_1.txz -s ",/.*/,,g" "*/pkg-static"

./pkg-static add ./pkg-1.1.4_1.txz


 for i in $(ls *txz); do
       pkg   add $i
     done

git clone git://github.com/definitly/mate.git

   cd mate

  ./start.sh



