#!/bin/sh


echo "введите iso: "
read iso
 

mdconfig -a -t vnode -u0 -f $iso  &&
mount /dev/md0 /mnt

echo "введите для продолжения любую клавишу:"
read a

umount /mnt
mdconfig -d -u 0
echo "введите для продолжения любую клавишу:"
read b


dd if=$iso  of=/dev/da0 bs=64k